### ISSUE TITLE
[Clarify Requirement] Table schema vs. Mockup data

### ISSUE THREAD

**Issue by cesc-vmo1802** [onqlavelabs/go-challenege#1]
![image](https://user-images.githubusercontent.com/104349332/189568155-051a48f3-1e45-44e9-919d-cb4a67e4ce3d.png)
![image](https://user-images.githubusercontent.com/104349332/189568275-90640d8e-6521-4b11-8de3-e50beed54fa8.png)
I see some different from table schema definition and example data. Could you confirm that one is correct?

**Comment by mattmahdieh** [comment]
Sure I will update the requirement..
